# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 762be95383581404346c8d1b49c0dcb710017ad2cfbe575702953dc7b9adec0df987c5cb2637840efad67c1b521e45543d42c6ecad2b79a1ed97f948a379368d

test:
  secret_key_base: 758047f180a4777868cc93100289903b5518c30e1754370328769cd720614d4357c518eb01dd01a35c6ffcb83d63195156bb5d5eed1278fd5ef2013dac6de401

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
